### ISSUE TITLE
Enable jaysvcutil to only generate a subset of entities

### ISSUE THREAD

**Issue by devkeydet** [jaystack/jaydata#100]
I have a huge OData service I need to interact with.  However, I only need a small subset of entities.  When I use jaysvcutil, my file is prohibitively large and initial load is slow.  Please either give me a cmd line switch where I can provide a comma separated list of entity names to include/exclude and/or the ability to point to a config file with similar ability.  Config file would be nice for reuse during dev as changes to the entities are made.

**Comment by jaydata** [comment]
Okay, I am putting this on the story board for 1.3.2 (1.3.1 is due to in days so I won't make it there). Do you know the feature `$data.service('mysite.com/myservice.svc', function(type, factory) { ...`? this is the dynamic jaysvcutil - an alternative to the jaysvcutil.exe. It comes in handy when the schema changes a lot, since it does what the jaysvcutil.exe would do - but on every application start.

**Comment by robesz** [comment]
This feature has been released with JayData 1.3.1 - JaySvcUtil 1.3.1 beta

http://jaydata.org/blog/jaysvcutil.exe-update%E2%80%93-filter-on-what-gets-imported-from-odata-metadata
