### ISSUE TITLE
Out-of-date NuGet package

### ISSUE THREAD

**Issue by ryanspletzer** [jaystack/jaydata#220]
1.3.6 release was February 2014, yet as of this post (June 2015) the NuGet package is still at 1.3.5. Is the NuGet feed still being maintained?

http://www.nuget.org/packages/JayData/

**Comment by ilyvion** [comment]
I'm starting to wonder if JayData itself is being maintained. No commits since April, before which the previous two commits were one in February and one in December last year... and their blog hasn't had a post since December last year either. Their forum is being overrun by spambots. Unless I see some drastic uptick in activity, I'm going to assume this project has been wholly abandoned.

**Comment by PeterAronZentai** [comment]
In fact we did not have much resources for this in the past months - that clearly shows.  The good news is that we are in the signature phase of a Series A investment that covers our following 2-3 year - so you'll see press releases and activity from October.

**Comment by ilyvion** [comment]
I'm glad to hear your product isn't dead. What you told us here seems like something that should've been a blog post... but on the other hand, I guess you're waiting until it's a sure thing—as you said—in October.

**Comment by PeterAronZentai** [comment]
Yes, you are right on that. We still haven't signed it but we have a date for the signature (the week of 20th of September). There are no major questions on the table so it would be quite surprising for all the parties to not have it signed as planned. Having all said that - it is still not a publicly releasable information - until it is in fact signed.

**Comment by robesz** [comment]
The new release is about to arrive in Nov-Dec
