### ISSUE TITLE
IEEE754Compatible=true Header

### ISSUE THREAD

**Issue by bstaley** [jaystack/jaydata#259]
We are using 1.5.5 having an issue around decimals and IEEE754Compatible. On post we get this error, '**Cannot convert a value to target type 'Edm.Decimal' because of conflict**'... If i pull the request into fiddler and add `IEEE754Compatible=true` to the `Content-Type` header the request goes through. I cannot find how to add/modify headers. Is it possible for jaydata just to do this automatically? You know if the type contains a decimal and even if you don't it should be configurable.

**Comment by yasmoradi** [comment]
```
let originalPrepareRequest = window['odatajs'].oData.utils.prepareRequest;
window['odatajs'].oData.utils.prepareRequest = function (request, handler, context) {
     request.headers = request.headers || {};
     let results = originalPrepareRequest.apply(this, arguments);
     if (request.headers['Content-Type'] == null)
          request.headers['Content-Type'] = "application/json";
     request.headers['Content-Type'] += ';IEEE754Compatible=true';
     return results;
 };
```

This is not enough, you can send your requests with decimal values to server using this approach, but there is a problem, when you receive a response from server which has a big decimal value in that.
Response is a json text, and ODataJS (a libray behind jaydata) will prase that into json object using json.parse in this method:
window['odatajs'].oData.json.jsonHandler.read
Json.parse will parse something like this : "{a:1}" to a object which has a |number| property named a
Because JavaScript's number type is limited, your data will be destroyed at this time.
So, you can do something like this:

```
let originalRead = window['odatajs'].oData.json.jsonHandler.read;

window['odatajs'].oData.json.jsonHandler.read = function (response, context) {

     if (response.body != null && typeof response.body === "string") {

          response.body = (response.body as string).replace(/:\s*(\d{14,}.\d{2,})\s*([,\}])/g, ':"$1"$2');

          // this will change something like "{ myDecimalProperty : 214748364711111.2 }" to "{ myDecimalProperty : '214748364711111.2' }"

      }

     return originalRead.apply(this, arguments);

}
```

So, before calling Json.parse, all your number values will be converted to string values, and your data will be remained safe,
Note that, Jaydata itself uses string for decimal values, but it has a guard for that, so you can't assing something like 'hello' to a decimal property, and because of being string, it won't lose data when json object gets mapped into jaydata entity.

Note that long (int64) values are bigger than JavaScript's number values too, my code will solve that problem too.

Good luck

**Comment by bstaley** [comment]
Thank you this was really helpful!!

**Comment by yasmoradi** [comment]
This works well with normal jaydata OData requests, but sub requests of batch requests ($batch) have their own headers, and my code does not affect those headers, so, batch request which comes with a child request, with a decimal value in its body, will fail. Use this code for now, but stay tuned. ;)

**Comment by yasmoradi** [comment]
Add following codes:

```
let originalJsonHandlerWrite = window['odatajs'].oData.json.jsonHandler.write;

                        window['odatajs'].oData.json.jsonHandler.write = function (request, context) {

                            if (request.headers['Content-Type'] == null)
                                request.headers['Content-Type'] = "application/json";

                            request.headers['Content-Type'] += ';IEEE754Compatible=true';

                            return originalJsonHandlerWrite.apply(this, arguments);

                        };
```

And add this if
`if (request.headers['Content-Type'].indexOf(";IEEE754Compatible=true") == -1)`
Before
`request.headers['Content-Type'] += ';IEEE754Compatible=true';`
This will solve the problem totally (-:

**Comment by bstaley** [comment]
Great, thanks for your help!
