### ISSUE TITLE
Safari 6 (desktop) bug

### ISSUE THREAD

**Issue by vicpon** [jaystack/jaydata#39]
In Safari 6 (browser or mobile), the jaydata framework does not load. It gives the following error:

"TypeError: Attempted to assign to readonly property."

I've searched online and people have commented that the use of "use strict" could cause this. So I looked for this text and found it in jaydata.js in the jslint section. After commenting that out, it doesn't give the error any more but it doesn't load the data provider. I'm using sqlite. I found that the xmlhttprequest returns status code 0 instead of 200, even though the responseText is set correctly to the contents of SqliteProvider.js. Not sure why it would return status code 0, but after adding it to the code it loaded the provider:

function loadScript(url, callback)  {
...
                    if (oXmlHttp.status == 200 || oXmlHttp.status == 304 || oXmlHttp.status == 0) {
                        eval.call(window, oXmlHttp.responseText);
                        if (typeof callback === 'function')
                            callback(true);
                    } else {
                        if (typeof callback === 'function') {
                            callback(false);
                        }
                    }
...
}

This works fine in the browser but does not work in PhoneGap. In PhoneGap, I get this error now:

"ReferenceError: Can't find variable: $data"

I've tried defining the model and creating the context before and after the deviceReady event has fired, neither works.

**Comment by jaydata** [comment]
Could you share your project that produces this error? Have this issue occured only with Safari 6?n How could someone get Safari 6 for mobile, I heard it's only on IOS 6 preview..

**Comment by vicpon** [comment]
Anyone with a Mac can get Safari 6. Unfortunately, there isn't going to be a Windows version. I will provide the code soon. By the way, none of the samples on the jaydata website work in Safari 6 either. They give the same error I mentioned above.

**Comment by vicpon** [comment]
On the phone I have Safari 5.1, not 6. I'll change the title

**Comment by jaydata** [comment]
Okay, thanks for the clarification. Good news I work on an iMac :) in OSX.

**Comment by vicpon** [comment]
I've put up a sample project that gives me the same errors. This is a PhoneGap project for iOS. Let me know if you have any problems with it

https://skydrive.live.com/redir?resid=46BA556ADF0A3029!105

**Comment by vicpon** [comment]
I've done some more research and a possible reason why the xmlhttprequest returns a status code of 0 is because it looks in the HTTP headers of the server response, which there isn't any. I think adding a check for a file URI type (file://) in combination with a non-empty response body would handle this correctly.

**Comment by PeterAronZentai** [comment]
Resolutions to this issue has been made. Principally it's two issues in one.
Issue 1 is a Safari6 "feature" coming down to the fact that Safari now throws an error if you try to set a field on a non-object type  value (like strings). Deep in the code of the JayLint file there was one occasion to this scenario. It has now been resolved. This fix can be downloaded from http://jaydata.codeplex.com/releases/view/91685 here look for a file called QuickFixForSafari6Bug. There's a complete jaydata file stack in the zip but only the jaydata.min.js and the jaydata.js file are relevant. Also note that this is a quickbuild and did not went through all the QA path a normal release does. The next JayData release will include this fix.
There is also a simple test application included so that you can check that the sql transactions are indeed working.

Issue 2 is that dynamic loading of the providers and modules (in this case sqlite provider) should not be used in Phonegap/Cordova. You simply need to include a script tag for every provider you are about use 

``` html
<script src="jaydata.js"></script>
<script src="jaydataproviders/SqLiteProvider.js"></script>
```

Make sure you are including scripts in the correct order, first jaydata, then any provider or module you are about to use.

I create an issue of this, so that JayData will alert if dynamic loading would occure in Cordova.

**Comment by PeterAronZentai** [comment]
Also, there is an example application in our  git repostiroy http://github.com/jaydata/JayScrum, this we build regularly to ios and android using Cordova. It has a simple one-table crud scenario impemented in websql/sqlite. This was working as of yesterday :)

**Comment by vicpon** [comment]
Sorry for the late response. Thanks for looking into this, Peter!

**Comment by PeterAronZentai** [comment]
No problem, i do hope it did fix your browser issues and also the Cordova project issue. please feel free to report back if something is not perfect.
