### ISSUE TITLE
How do I build from source?

### ISSUE THREAD

**Issue by floydpink** [jaystack/jaydata#58]
This is not an issue, but just a question for the developers. After I fork from the repo what is the process to get the current jaydata.js (along with the providers and other dependent modules)?

**Comment by agdolla** [comment]
Sorry if it is not clear from the documentation :(
Our typical users download the released version which is prebuilt and never have to build the library themself. Also we've just started our CDN so users do not even have to download the library but it is enough to reference to our CDN from the html. So you have to build the library yourself only if you want to use a non-released version such as the latest from git.
You do not have to fork it, but of course you can. If you only want to build the latest version it is enough to clone the repository to your machine.
On a linux or osx box just issue 'make'. On a windows box it is hard to build, because the necessary tools are usually missing, but if you can build it on linux/osx, you can copy the files to your windows box. Linux can be run virtualized in VirtualBox or VMWare Player/Workstation or HyperV.
If you really can't/won't build it yourself you can use our build repo as a last resort. You can find it here: jaydata-build.s3.amazonaws.com. I update it non-regularly :( so I would not call it nightly build.  I've just updated it, so the latest file is: http://jaydata-build.s3.amazonaws.com/jaydata-20121114081804.zip.

**Comment by robesz** [comment]
Hello @floydpink ,
Did you get the expected answer to your question?
You can find more information about the CDN in the release notes blogpost: http://jaydata.org/blog/release-notes

Please let us know if you need more help or I can close this issue.
Regards,
Robert

**Comment by oising** [comment]
This is a pity - this should be buildable on all platforms - it's just javascript... sigh.

**Comment by PeterAronZentai** [comment]
This one annoys me a lot too... what if Santa would bring a build.bat? It is really a bunch of xcopy and copy+  truth be told - why can't windows support such a thing like apt-get install buildessentials? And then I could just make. sigh.

**Comment by oising** [comment]
This is not windows' fault. :)
