### ISSUE TITLE
sqLite provider unable to reconstruct relationships without inverseproperty?

### ISSUE THREAD

**Issue by oising** [jaystack/jaydata#68]
Is this true? I have a large graph of entities with navigation properties that are one way. If I try to retrieve the root entities from the provider, ensuring I use `include("NavigationPropertyName")` then I get failures:

```
w = m.context.InspectionSheets
    .include("Data")
    .forEach(function(s) { console.log(s); });

w.state()
"rejected"

w.fail(function(r) { console.log(r); })

SQLError {message: "could not prepare statement (1 near "$$unbound__Id": syntax error)", code: 5}
```

I have to say that I'm really disappointed in jaydata so far - you guys are focusing on _breadth_ at the expense of _depth_. That is to say, you do many, many things, but not very well. Who really cares about YQL? Drop it and focus on the core providers like oData and SQLite/WebSQL. This should be your bread and butter.

**Comment by PeterAronZentai** [comment]
Inverse properties are mandatory - the  guessing logic has been dropped - it was not working reliably. I understand that this makes using these features less convenient - but let's be frank  - it's not rendering the feature inoperational, just less convenient to define (1% of the time you are defining things and 99% of the time you are using it).

JayData is a cross storage provider, we try to balance in reaching as many storage sources as possible and to provide deep functionality per each provider. This is not so simple and our capacity is not limitless. JayData is created as a free, open source project. While it certainly has limitations it also has features that work just great and spare your or me a lot of time. But this is not the stone of the mages and may not cover in 100% everyone's needs - no matter how much work is put into it. 

Anyway regarding your suggestion: YQL provider is not developed actively, efforts do go into sqLite and OData and now into webAPI.  And also into IndexedDB  that will surely replace webSql very soon, sooner the we anticipated a year ago. Check Chrome's new appliction platform the Chrome Packaged Apps - no webSQL support.

**Comment by oising** [comment]
Hi Peter

Thanks for the prompt reply. Please don't mistake my open irritation as being over the requirement for inverse properties for the irritation of spending many hours determining this limitation. Debugging nearly 20,000 lines of obtuse javascript in a browser (chrome 23) that crashes at the drop of a hat will do that to a man.

I am not a stranger to open source development ( http://www.codeplex.com/site/users/view/oisin ) so I greatly appreciate your patience with me, and I will openly admit that jaydata is one of the most (if not the most) advanced libraries out there for data. Your documentation is better than most, but I've had a trying week - having to spend the best part of a day provisioning an ubuntu image with all the relevant tools just to build your javascript was not a good start, but I think you're trying to cover that at the moment.

Good documentation is pretty hard to keep sync'd with a rapid iterative process, but if I might suggest, you would do well to at least build out a full feature matrix for all providers showing what works where, and what the requirements are etc. I was bitten this week a few times by undocumented disparities (like .include("a.b") not working in sqLite). Anyway, keep up the good work and I'll keep logging the issues. 

Thanks.

**Comment by PeterAronZentai** [comment]
Oisin, 

That sounds really like a week of massive frustration. While we are not able to make it undone, we will try making this up for you with whatever help we can throw in into your project. We  can be connected by phone or by Skype and most of the time I am or a colleague of mine will be more then eager to jump into some shared screen debugging - of things really turn sour. What you are doing is very important to us, and to the library: you are pushing things to their limits and that helps us identify problems more easily. But that also means that both parties will shed some blood. So thank you for any efforts submitting us the issues you experience.

BTW: We do have a very conservative feature matrix here: http://jaydata.org/tutorials/jaydata-api-features, this does not lists sqLite include operator capabilities  - even if it does work on a limited way. This is because there were some issues with the recursion of the model binder  when it operated over data coming from multiple left outers or joins. We have put this issue into the priority stack since you requested, so in the first week of january we release 1.2.7 with better sqLite include support.

**Comment by robesz** [comment]
The feature has been relesed and the api feature matrix has been updated.

**Comment by oising** [comment]
Congratulations :)
