### ISSUE TITLE
asKendoDataSource() fails when using the map operator

### ISSUE THREAD

**Issue by ondrejsv** [jaystack/jaydata#74]
This code

``` javascript
            var ds = ctx.ProductCategories
                .map(function (category) {
                return { Name: category.Name, Id: category.ProductCategoryID };
                })
                .asKendoDataSource();
```

breaks on SCRIPT438: Object doesn't support property or method 'asKendoObservable' 
kendo.js, line 297 character 25

When the map operator is commented out, it works as expected:

``` javascript
            var ds = ctx.ProductCategories
                //.map(function (category) {
                //return { Name: category.Name, Id: category.ProductCategoryID };
                //})
                .asKendoDataSource();
```

**Comment by agdolla** [comment]
Hi

map() returns anonymous objects by default but you can tell map to return objects of specified type.

``` javascript

     var ds = ctx.ProductCategories
                .map(function (category) {
                    return { Name: category.Name, ProductCategoryID: category.ProductCategoryID };
                }, {}, ctx.ProductCategories.elementType)
                .asKendoDataSource();

```

be sure that you do not filter out the primary key as it is needed to kendo

**Comment by agdolla** [comment]
We plan to extend our documentation about these features, sorry, our documentation does not cover everything now.
There is one thing that is tricky:
You can use filter with kendodatasource, like:
    ctx.ProductCategories.filter()......asKendoDataSource()
or even you can use many filters
    ctx.ProductCategories.filter().filter().filter().....asKendoDataSource()

If you use kendo's own filter for example in grid the filters are added together, so you can think of the filters specified at the datasource declaration as prefilters, for example:
    ctx.ProductCategories.filter(function(category){return category.iswholesale==true;}).asKendoDataSource()
and you use it in a grid then only those categories will be displayed where iswholesale==true.
Then you can filter them further using the grid filter function, for example 'Name contains computer' and then only those categories will be listed where both  iswholesale==true and  'Name contains computer' are true.

You can also combine filter with other features like map, include, etc but if you want to use both jaydata filter and kendo filter then you need to deviate from jaydata's usual pattern and specify filter(s) last, so instead of
    ctx.ProductCategories.filter().map()..asKendoDataSource()
you must use
    ctx.ProductCategories.map().filter()..asKendoDataSource()

**Comment by PeterAronZentai** [comment]
when using map() you can fall back to the default model type using "default" as the type parameter, like this:

``` javascript
filter(predicate).map( projection, {}, "default")
```

In version 1.3 we plan to add a smart guessing of the projected type, and also the `new` operator in the projection, so that you could as well write:

``` javascript
Products.map(function(it) { return new SomeType({name: it.ProductName});
```

**Comment by ondrejsv** [comment]
Thank you guys for your explanations. Some docs would be really helpful :)

**Comment by ruudsolidnl** [comment]
Hi,
I'm also struggling with the .asKendoDataSource. I use the typescript generation in the JaySvcUtil-1.4.0-alpha.exe (works great btw). Both js and d.ts files are embedded in the project. Now, when i try to use the asKendoDataSource function, i get the following error:

"Uncaught TypeError: this.defaultType.asKendoModel is not a function
    at EntitySet.asKendoModel (local://simulator/scripts/kendo.js:416:33)
    at EntitySet.asKendoDataSource (local://simulator/scripts/kendo.js:688:26)
    at <anonymous>:2:25
    at Object.InjectedScript._evaluateOn (<anonymous>:895:140)
    at Object.InjectedScript._evaluateAndWrap (<anonymous>:828:34)
    at Object.InjectedScript.evaluate (<anonymous>:694:21)"

This error occurs also when used solely in Js. Any ideas? I agree with Ondrejsv that some documentation will help, as I am quite new to Js development (the reason I chose a framework like JayData :)). The examples I found of both Telerik and JayData refer to another way of instantiating the data context. Thanks in advance.

Best regards,
Ruud
