### ISSUE TITLE
Saving Data To A Table with more than 1 FK relationship

### ISSUE THREAD

**Issue by mohammadchehab** [jaystack/jaydata#85]
Am trying to sync data from the server. JayData offers a very nice way in doing so. However when i stumbled with a table that has 2 relationships i tried to insert the parent table first then the child table however that failed always.
How do you implement it ?
Here is the entities and the tables.
I want to insert data in the vObject and vOperation and vObjectOperation

![2013-02-09_1429](https://f.cloud.github.com/assets/1060227/141974/c3a53b16-72a3-11e2-8bd7-28e8a1c04107.png)

$data.Entity.extend('PlannerModel.vOperation', {
        'Operation_Code': { key: true, type: 'Edm.String', nullable: false, required: true },
        'Operation_Name': { type: 'Edm.String', nullable: false, required: true },
        'vMasterPlanners': { type: 'Array', elementType: 'PlannerModel.vMasterPlanner', inverseProperty: 'vOperation' },
        'vObjectOperations': { type: 'Array', elementType: 'PlannerModel.vObjectOperation', inverseProperty: 'vOperation' }
    });
    $data.Entity.extend('PlannerModel.vObjectOperation', {
        'Object_ID': { key: true, type: 'Edm.String', nullable: false, required: true },
        'Operation_Code': { key: true, type: 'Edm.String', nullable: false, required: true },
        'Period': { key: true, type: 'Edm.Int32', nullable: false, required: true },
        'Crew_ID': { key: true, type: 'Edm.String', nullable: false, required: true },
        'vOperation': { type: 'PlannerModel.vOperation', required: true, inverseProperty: 'vObjectOperations' },
        'vObject': { type: 'PlannerModel.vObject', required: true, inverseProperty: 'vObjectOperations' }
    });
    $data.Entity.extend('PlannerModel.vObject', {
        'Object_ID': { key: true, type: 'Edm.String', nullable: false, required: true },
        'Object_Name': { type: 'Edm.String', nullable: false, required: true },
        'vMasterPlanners': { type: 'Array', elementType: 'PlannerModel.vMasterPlanner', inverseProperty: 'vObject' },
        'vObjectOperations': { type: 'Array', elementType: 'PlannerModel.vObjectOperation', inverseProperty: 'vObject' }
    });

The problem is every time i try to insert i get sql error constraint.

PS: Inserting the vObject and vOperation works just fine.

**Comment by PeterAronZentai** [comment]
Can you share the code for syncing vObjectOperations? Are you setting the nav properties back? 

A simple workaround that you might try is this:
context.vObjectOperations.include("it.vObject").include("it.vOperation").toArray(function(items) {
    localStore.vObjectOperations.addMany(items);
    localStore.saveChanges();
});

The best way to share code is gist, please upload you context definition and the actual code that missbehaves.
thanks
Peter

**Comment by mohammadchehab** [comment]
i will try it and let you know

**Comment by PeterAronZentai** [comment]
Your model definition contains an entity with a compound PK. This use case is not supported by IE10-IndexedDB implementation. Keep this in mind! Also navigation properties will be a new feature to our IndexedDB provider to be released end of Feb. In case you would need indexeddb support these are good to know. If you are only targetting Androids and IPhones that this does not apply.

**Comment by PeterAronZentai** [comment]
In the meantime i just started a repro on this so that we minimize "wild guesses". I'll let you know my finding...

**Comment by mohammadchehab** [comment]
it worked :+1:  and regarding target currently am interested in android and iphones but yet other platforms should be included in the future releases of the app.

**Comment by mohammadchehab** [comment]
your a pure genius !

**Comment by PeterAronZentai** [comment]
:) you mean the library :) thanks, your feedback is highly appreciated

**Comment by mohammadchehab** [comment]
and everything that comes with it :D

**Comment by mohammadchehab** [comment]
is There any other way for inserting into a table with multiple FKs?

**Comment by mohammadchehab** [comment]
When am doing so a huge amont of data is coming to to the app making it crash.
if I could insert table by table that would be much better however i have the FK constraint issue. So what are the suggestions ?

**Comment by PeterAronZentai** [comment]
I am creating a guide on this. Indeed this can be tricky.. I'll show you a way that let's you sync an unlimited number of items (within the device limits) with paging and windowing...

**Comment by mohammadchehab** [comment]
Amazing. Id love so please keep me updated soon cause i really need this.

**Comment by agdolla** [comment]
You can do it in batches, somethink like this (just a poc, might need some polish)

``` javascript
var batchsize=1000;
function saveBatch(start, length) {
   if (start > length) return;
   return context.vObjectOperations
      .include("it.vObject")
      .include("it.vOperation")
      .skip(start)
      .take(batchsize)
      .toArray()
   .then(function(items) {
       localStore.vObjectOperations.addMany(items);
       return localStore.saveChanges();
    })
    .then(function() {
        return saveBatch(start + batchsize, length);
    })
}

context.vObjectOperations.length()
.then(function(length) {
    return saveBatch(0, length);
})
```

**Comment by PeterAronZentai** [comment]
This is a quick way to do it but it'll most likely work. What I am creating is a more generic approach that is more scalable and generates less network payload (only syncs outers once).

**Comment by mohammadchehab** [comment]
This seems very interesting. Just one remaining issue what happens to the child table that has these 2 FKs ?

**Comment by agdolla** [comment]
also, to use paging, your backend must support length or inlineCount

**Comment by mohammadchehab** [comment]
This one am supporting

**Comment by agdolla** [comment]
Sorry, but I do not understand this part: "Just one remaining issue what happens to the child table that has these 2 FKs ".

**Comment by PeterAronZentai** [comment]
I have prepped a more complex sync implementation that handles foreign keys a bit differently You can download it from here: http://jaydata.org/examples/NorthwindSyncDemo.zip

I  would be happy to go through with you over the implementation details as it touches some advanced scenarios like promises.

Overall the code is not as simple as I expected this to be. This comes from three things
- Published Foreign Keys as Primary Keys needs special data declaration in JayData (check OrderDetail entity definition in the localdb.js). This breaks local-remote type sharing so I had to create a separate type set for localdb. This is one improvement we would recommend as prior.
- This example is generic, will work with or without Published Foreign Key fields since it uses projection
- The example since using projection provides a faster bulkinsert mechanism, as you dont have to load the foreign  entity to be able to set it on the parent entity.

**Comment by mohammadchehab** [comment]
This is an absolutely amazing way to deal with it. I had no idea about the $data.service. I think this solution is a killer!!

Thanks you so much !

**Comment by Konbonix** [comment]
@PeterAronZentai Hey Peter, It's probably a long shot as it has been years since you posted the example and wrote this [blogpost](https://jaydata.org/blog/synchronized-onlineoffline-data-applications-part-2-syncing-large-tables-and-tables-with-foreign-relations) - but is the NorthWindSyncDemo.zip still available anywhere? The JayData.org website now returns 404 when trying to download it from [http://jaydata.org/examples/NorthwindSyncDemo.zip](http://jaydata.org/examples/NorthwindSyncDemo.zip).

I'm working on a legacy project that uses jQuery + JayData and trying to build an offline sync mode, but your NorthWindSync example and all the jQuery example projects on https://jaydata.org/examples are all dead links. I've also dug through the JayStack GitHub repositories but can't seem to find any other examples that showcase an offline sync. So if you happen to still have the NorthWindSync files around and could share them I would greatly appreciate it.
