### ISSUE TITLE
Deferred URI query for OData

### ISSUE THREAD

**Issue by ghost** [jaystack/jaydata#89]
(not sure if this was asked already)
Hey i am using Asp.net Web Api with the OData extension which currently doesn't support $expand (not that i know of). 
When i use the jaydata native .include("Property"), its broken down to a $expand.
I was wondering if there is a way in jaydata to yield a request query such as the following:

http://localhost:6962/odata/Accounts(1)/Membership

Which will bring up the specific membership object for the Account of ID=1.

Please advise me of the best way currently to resolve such an issue
Thanks in advance

**Comment by robesz** [comment]
Hello Layton,

you can query the Memembership collection instead of the Account, this won't use $expand.
something like this:

this.Memberships.filter(function(m) { return m.Id == <Account.MemberShipId>});
or
this.Memberships.filter(function(m) { return m.AccountId == <Account.Id>});

The field names between the <>placeholders should be changed according to your model.

**Comment by ghost** [comment]
yea i figured that out.but thanks for the reply though

**Comment by ghost** [comment]
Layton Whiteley sent you an invitation

Twitter helps you stay connected with what's happening right now and with the people and organizations you care about.

```
Accept invitation
```

https://twitter.com/i/c69ee756-1c2d-4929-8e0d-530c3357aaa7

## 

This message was sent by Twitter on behalf of Twitter users who entered your email address to invite you to Twitter.
Unsubscribe: https://twitter.com/i/o?t=1&iid=0209351eed834f9a966e91a76924cdb8&uid=0&c=IuVwbCB3dgExbd0GyL%2FKRYKpsrPSjIPN%2FdFOzPQF%2FTOP%2B%2BFgqpxnv7I1dbLLDtgjesByX2yM%2BLaKvSmpqGFtFgbfnN5w8UmYsmhZE0AexKdXsdvPTS4%2Beg%3D%3D&nid=9+26

Need help?
https://support.twitter.com
